monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@test:
    monolog:
        handlers:
            main:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
                channels: ['!event']
            stderr:
                type: stream
                path: php://stderr
                level: error
                channels: ['!event']
            console:
                type: console
                process_psr_3_messages: true
                channels: ['!event', '!doctrine', '!console']

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
                channels: ['!event']
            console:
                type: console
                process_psr_3_messages: true
                channels: ['!event', '!doctrine', '!console']

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
                process_psr_3_messages: true
                formatter: 'monolog.formatter.json'

            nested:
                type: stream
                path: php://stderr
                level: debug

            console:
                type: console
                process_psr_3_messages: true
                channels: ['!event', '!doctrine', '!deprecation']
                formatter: 'monolog.formatter.json'
