name: Publish Docker Image

on:
    push:
        tags:
            - "latest"
            - "v*"

    workflow_dispatch:

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest

        env:
            DOCKER_BUILDKIT: 1

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: ${{ secrets.DOCKER_USERNAME }}/database-dumper
                  tags: |
                      type=raw,value=latest
                      type=ref,event=tag,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
